# Generated by Django 3.0.8 on 2020-07-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Hari', max_length=50)),
                ('last_name', models.CharField(default='Bahadur', max_length=50)),
                ('nepal_address', models.CharField(choices=[('GK', 'Gorkha'), ('NPJG', 'Nepaljung'), ('KTM', 'Kathmandu'), ('BTW', 'Butwal'), ('CHW', 'Chitwan')], db_column='home_address', db_index=True, default='KTM', max_length=4)),
                ('cv', models.FileField(null=True, upload_to='uploads/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='firstApp.Membership', to='firstApp.Person'),
        ),
    ]
