# Generated by Django 3.0.8 on 2020-07-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20200704_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.Car'),
        ),
    ]
