# Generated by Django 3.0.8 on 2020-07-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20200704_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='firstApp.Person'),
        ),
    ]
