# Generated by Django 3.0.8 on 2020-07-05 12:21

from django.db import migrations, models
import modelExtra.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelExtra', '0002_auto_20200705_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='age',
            field=models.IntegerField(validators=[modelExtra.models.validate_my_age]),
        ),
    ]
